module ApplicationHelper
  def alert_check key
    if key == "alert" then
      return "warning"
    elsif key == "notice" then
      return "info"
    else return ""
    end
  end

  def yesno(x)
    x ? "Yes" : "No"
  end
  def security_questions
    [['What is your favorite color?', 0],
     ['What was the make and model of your first car?', 1]]
  end
  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end
  def countries

            ['Andorra',
             'United Arab Emirates',
             'Afghanistan',
             'Antigua and Barbuda',
             'Anguilla',
             'Albania',
             'Armenia',
             'Netherlands Antilles',
             'Angola',
             'Antarctica',
             'Argentina',
             'American Samoa',
             'Austria',
             'Australia',
             'Aruba',
             'Aland Islands',
             'Azerbaijan',
             'Bosnia and Herzegovina',
             'Barbados',
             'Bangladesh',
             'Belgium',
             'Burkina Faso',
             'Bulgaria',
             'Bahrain',
             'Burundi',
             'Benin',
             'Saint Barthélemy',
             'Bermuda',
             'Brunei',
             'Bolivia',
             'British Antarctic Territory',
             'Brazil',
             'Bahamas',
             'Bhutan',
             'Bouvet Island',
             'Botswana',
             'Belarus',
             'Belize',
             'Canada',
             'Cocos Islands',
             'Congo - Kinshasa',
             'Central African Republic',
             'Congo - Brazzaville',
             'Switzerland',
             'Ivory Coast',
             'Cook Islands',
             'Chile',
             'Cameroon',
             'China',
             'Colombia',
             'Costa Rica',
             'Serbia and Montenegro',
             'Canton and Enderbury Islands',
             'Cuba',
             'Cape Verde',
             'Christmas Island',
             'Cyprus',
             'Czech Republic',
             'East Germany',
             'Germany',
             'Djibouti',
             'Denmark',
             'Dominica',
             'Dominican Republic',
             'Algeria',
             'Ecuador',
             'Estonia',
             'Egypt',
             'Western Sahara',
             'Eritrea',
             'Spain',
             'Ethiopia',
             'Finland',
             'Fiji',
             'Falkland Islands',
             'Micronesia',
             'Faroe Islands',
             'French Southern and Antarctic Territories',
             'France',
             'Metropolitan France',
             'Gabon',
             'United Kingdom',
             'Grenada',
             'Georgia',
             'French Guiana',
             'Guernsey',
             'Ghana',
             'Gibraltar',
             'Greenland',
             'Gambia',
             'Guinea',
             'Guadeloupe',
             'Equatorial Guinea',
             'Greece',
             'South Georgia and the South Sandwich Islands',
             'Guatemala',
             'Guam',
             'Guinea-Bissau',
             'Guyana',
             'Hong Kong SAR China',
             'Hong Kong',
             'Heard Island and McDonald Islands',
             'Honduras',
             'Croatia',
             'Haiti',
             'Hungary',
             'Indonesia',
             'Ireland',
             'Israel',
             'Isle of Man',
             'India',
             'British Indian Ocean Territory',
             'Iraq',
             'Iran',
             'Iceland',
             'Italy',
             'Jersey',
             'Jamaica',
             'Jordan',
             'Japan',
             'Johnston Island',
             'Kenya',
             'Kyrgyzstan',
             'Cambodia',
             'Kiribati',
             'Comoros',
             'Saint Kitts and Nevis',
             'North Korea',
             'South Korea',
             'Kuwait',
             'Cayman Islands',
             'Kazakhstan',
             'Laos',
             'Lebanon',
             'Saint Lucia',
             'Liechtenstein',
             'Sri Lanka',
             'Liberia',
             'Lesotho',
             'Lithuania',
             'Luxembourg',
             'Latvia',
             'Libya',
             'Morocco',
             'Monaco',
             'Moldova',
             'Montenegro',
             'Saint Martin',
             'Madagascar',
             'Marshall Islands',
             'Midway Islands',
             'Macedonia',
             'Mali',
             'Myanmar',
             'Mongolia',
             'Macau SAR China',
             'Macau',
             'Northern Mariana Islands',
             'Martinique',
             'Mauritania',
             'Montserrat',
             'Malta',
             'Mauritius',
             'Maldives',
             'Malawi',
             'Mexico',
             'Malaysia',
             'Mozambique',
             'Namibia',
             'New Caledonia',
             'Niger',
             'Norfolk Island',
             'Nigeria',
             'Nicaragua',
             'Netherlands',
             'Norway',
             'Nepal',
             'Dronning Maud Land',
             'Nauru',
             'Neutral Zone',
             'Niue',
             'New Zealand',
             'Oman',
             'Panama',
             'Pacific Islands Trust Territory',
             'Peru',
             'French Polynesia',
             'Papua New Guinea',
             'Philippines',
             'Pakistan',
             'Poland',
             'Saint Pierre and Miquelon',
             'Pitcairn',
             'Puerto Rico',
             'Palestinian Territory',
             'Portugal',
             'U.S. Miscellaneous Pacific Islands',
             'Palau',
             'Paraguay',
             'Panama Canal Zone',
             'Qatar',
             'Outlying Oceania',
             'European Union',
             'Reunion',
             'Romania',
             'Serbia',
             'Russia',
             'Rwanda',
             'Saudi Arabia',
             'Solomon Islands',
             'Seychelles',
             'Sudan',
             'Sweden',
             'Singapore',
             'Saint Helena',
             'Slovenia',
             'Svalbard and Jan Mayen',
             'Slovakia',
             'Sierra Leone',
             'San Marino',
             'Senegal',
             'Somalia',
             'Suriname',
             'Sao Tome and Principe',
             'Union of Soviet Socialist Republics',
             'El Salvador',
             'Syria',
             'Swaziland',
             'Turks and Caicos Islands',
             'Chad',
             'French Southern Territories',
             'Togo',
             'Thailand',
             'Tajikistan',
             'Tokelau',
             'East Timor',
             'Turkmenistan',
             'Tunisia',
             'Tonga',
             'Turkey',
             'Trinidad and Tobago',
             'Tuvalu',
             'Taiwan',
             'Tanzania',
             'Ukraine',
             'Uganda',
             'United States Minor Outlying Islands',
             'United States',
             'Uruguay',
             'Uzbekistan',
             'Vatican',
             'Saint Vincent and the Grenadines',
             'North Vietnam',
             'Venezuela',
             'British Virgin Islands',
             'U.S. Virgin Islands',
             'Vietnam',
             'Vanuatu',
             'Wallis and Futuna',
             'Wake Island',
             'Samoa',
             'People\'s Democratic Republic of Yemen',
              'Yemen',
             'Mayotte',
             'South Africa',
             'Zambia',
             'Zimbabwe',
             'Unknown or Invalid Region']

  end
end
